pub mod grade_service_impl;
pub mod semester_service_impl;
pub(crate) mod system_config_service_impl;
pub mod textbook_service_impl;
pub mod textbook_version_service_impl;
pub mod unit_service_impl;
pub mod word_service_impl;
pub mod word_unit_service_impl;
pub(crate) mod model_provider_service_impl;
